title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This site couldn't possible get any better. But wait, there's more...

# social links
twitter_username: @thebutt
github_username:  zurstadt

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
